# -*- coding: utf-8 -*-
"""Wordle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CB_ls6TAtMZhpjsTNDQh8jJAdklhvkRA
"""

import random

word_dict = ['Abuse', 'Adult', 'Agent', 'Anger','Apple','Award','Basis','Beach','Birth','Block','Blood','Board','Brain','Bread','Break','Brown','Buyer','Cause','Chain','Chair','Chest','Chief','Child''China','Claim',
'Class',
'Clock',
'Coach',
'Coast',
'Court',
'Cover',
'Cream',
'Crime',
'Cross',
'Crowd',
'Crown',
'Cycle',
'Dance',
'Death',
'Depth',
'Doubt',
'Draft',
'Drama',
'Dream',
'Dress',
'Drink',
'Drive',
'Earth',
'Enemy',
'Entry',
'Error',
'Event',
'Faith',
'Fault',
'Field',
'Fight',
'Final',
'Floor',
'Focus',
'Force',
'Frame',
'Frank',
'Front',
'Fruit',
'Glass',
'Grant',
'Grass',
'Green',
'Group',
'Guide',
'Heart',
'Henry',
'Horse',
'Hotel',
'House',
'Image',
'Index',
'Input',
'Issue',
'Japan',
'Jones',
'Judge',
'Knife',
'Laura',
'Layer',
'Level',
'Lewis',
'Light',
'Limit',
'Lunch',
'Major',
'March',
'Match',
'Metal',
'Model',
'Money',
'Month',
'Motor',
'Mouth',
'Music',
'Night',
'Noise',
'North',
'Novel',
'Nurse',
'Offer',
'Order',
'Other',
'Owner',
'Panel',
'Paper',
'Party',
'Peace',
'Peter',
'Phase',
'Phone',
'Piece',
'Pilot',
'Pitch',
'Place',
'Plane',
'Plant',
'Plate',
'Point',
'Pound',
'Power',
'Press',
'Price',
'Pride',
'Prize',
'Proof',
'Queen',
'Radio',
'Range',
'Ratio',
'Reply',
'Right',
'River',
'Round',
'Route',
'Rugby',
'Scale',
'Scene',
'Scope',
'Score',
'Sense',
'Shape',
'Share',
'Sheep',
'Sheet',
'Shift',
'Shirt',
'Shock',
'Sight',
'Simon',
'Skill',
'Sleep',
'Smile',
'Smith',
'Smoke',
'Sound',
'South',
'Space',
'Speed',
'Spite',
'Sport',
'Squad',
'Staff',
'Stage',
'Start',
'State',
'Steam',
'Steel',
'Stock',
'Stone',
'Store',
'Study',
'Stuff',
'Style',
'Sugar',
'Table',
'Taste',
'Terry',
'Theme',
'Thing',
'Title',
'Total',
'Touch',
'Tower',
'Track',
'Trade',
'Train',
'Trend',
'Trial',
'Trust',
'Truth',
'Uncle',
'Union',
'Unity',
'Value',
'Video',
'Visit',
'Voice',
'Waste',
'Watch',
'Water',
'While',
'White',
'Whole',
'Woman',
'World',
'Youth']

word_dict_span = len(word_dict)

word = word_dict[random.randint(0, word_dict_span - 1)]

print(' Wordle Game '.center(40, '*'))
print('X indicates the correct letter and position.')
print('O indicates the letter is in the word, but in the wrong position.')
print('_ indicates that the letter is not in the word.\n')

print('You are to input a 5 letter word. You have 6 tries.')

for i in range(6):
    count = 0
    player_input = input('Enter the word: ').lower()

    if len(player_input) == 5:
        for j in player_input:
            if j in word:
                if word[count] == j:
                    print('X', end='')
                else:
                    print('O', end='')
            else:
                print('_', end='')

            count = count + 1

        if player_input == word:
            print('\nYou won')
            break

        if i == 5 and player_input != word:
            print('\nSorry, you lost. The word is', word)

        print('\n')

    else:
        print('Invalid entry! Enter a five letter word.')
        continue